### ISSUE TITLE
Problem with saving into an existing file

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#179]
1) Open SBOLDesigner
2) Built ColE1_P15A
3) Select CqsS_Gene, and press magnifying glass + to go inside
4) Built CqsS_Gene
5) Select ColE1, and press magnifying glass + to go inside
6) Built ColE1 
7) Saved by clicking fifth icon (“Save your current design”), typed in a new file name to save to

No problem so far.

8) Made a small edit, and tried to save again, and I get the error message you have.

Michael: the issue appears to be a problem with saving into an existing document, and it looks like it has to do with the Activity for Prov-O getting saved (see exception below).

org.sbolstandard.core2.SBOLValidationException: sbol-10202: The identity property of an Identified object MUST be globally unique.
Reference: SBOL Version 2.1.0 Section 7.4 on page 17
: http://www.async.ece.utah.edu/CqsS_Gene_SBOLDesigner/1
	at org.sbolstandard.core2.SBOLDocument.addTopLevel(SBOLDocument.java:2557)
	at org.sbolstandard.core2.SBOLDocument.addGenericTopLevel(SBOLDocument.java:2055)
	at org.sbolstandard.core2.SBOLDocument.createGenericTopLevel(SBOLDocument.java:2008)
	at org.sbolstandard.core2.SBOLDocument.createCopy(SBOLDocument.java:1326)
	at org.sbolstandard.core2.SBOLDocument.createCopy(SBOLDocument.java:1163)
	at org.sbolstandard.core2.SBOLDocument.createCopy(SBOLDocument.java:1139)
	at edu.utah.ece.async.sboldesigner.sbol.SBOLUtils.insertTopLevels(SBOLUtils.java:465)
	at edu.utah.ece.async.sboldesigner.sbol.editor.SBOLDesignerPanel.saveIntoExistingFile(SBOLDesignerPanel.java:727)

**Comment by cjmyers** [comment]
I've added a check for existing GenericTopLevels and it now removes them too on overwrite.

**Comment by michael13162** [comment]
I have tested and confirmed that your fix works.  I have also updated the release on GitHub with a newly built jar.  Thanks!
