### ISSUE TITLE
Unable to save due to duplicate provenance information

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#225]
I created a part.  Saved it.  Opened it.  Edited it. Saved again. Got this exception.  You need to check for the Activity before trying to create it again to make sure you don't get duplicate URIs.

org.sbolstandard.core2.SBOLValidationException: sbol-10202: The identity property of an Identified object MUST be globally unique.
Reference: SBOL Version 2.2.0 Section 7.4 on page 17
: http://async.ece.utah.edu/TestDevice1_SBOLDesignerActivity/Association/1
	at org.sbolstandard.core2.Identified.addChildSafely(Identified.java:809)
	at org.sbolstandard.core2.Activity.addAssociation(Activity.java:491)
	at org.sbolstandard.core2.Activity.createAssociation(Activity.java:85)
	at org.sbolstandard.core2.Activity.createAssociation(Activity.java:106)
	at edu.utah.ece.async.sboldesigner.sbol.ProvenanceUtil.createProvenance(ProvenanceUtil.java:71)
	at edu.utah.ece.async.sboldesigner.sbol.editor.SBOLDesign.createDocument(SBOLDesign.java:1346)
	at edu.utah.ece.async.sboldesigner.sbol.editor.SBOLDesignerPanel.saveIntoExistingFile(SBOLDesignerPanel.java:504)
	at edu.utah.ece.async.sboldesigner.sbol.editor.SBOLDesignerPanel.save(SBOLDesignerPanel.java:455)
	at edu.utah.ece.async.sboldesigner.sbol.editor.SBOLDesignerPanel$6.perform(SBOLDesignerPanel.java:159)
	at edu.utah.ece.async.sboldesigner.sbol.editor.SBOLEditorAction.actionPerformed(SBOLEditorAction.java:91)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by cjmyers** [comment]
Hmm, you are actually looking for the association I see, and it is there:

<prov:Activity rdf:about="http://async.ece.utah.edu/TestDevice1_SBOLDesignerActivity/1">
    <sbol:persistentIdentity rdf:resource="http://async.ece.utah.edu/TestDevice1_SBOLDesignerActivity"/>
    <sbol:displayId>TestDevice1_SBOLDesignerActivity</sbol:displayId>
    <sbol:version>1</sbol:version>
    <dc:creator>Chris J. Myers</dc:creator>
    <prov:endedAtTime>2018-01-17T15:24:47.733-07:00</prov:endedAtTime>
    <prov:qualifiedAssociation>
      <prov:Association rdf:about="http://async.ece.utah.edu/TestDevice1_SBOLDesignerActivity/Association/1">
        <sbol:persistentIdentity rdf:resource="http://async.ece.utah.edu/TestDevice1_SBOLDesignerActivity/Association"/>
        <sbol:displayId>Association</sbol:displayId>
        <sbol:version>1</sbol:version>
        <prov:hadRole rdf:resource="http://sbols.org/v2#sequenceEditor"/>
        <prov:agent rdf:resource="https://synbiohub.org/public/SBOL_Software/SBOLDesigner/2.2"/>
      </prov:Association>
    </prov:qualifiedAssociation>
  </prov:Activity>

I guess you might also want to verify that the id is not in use too.  Though seems there might be another issue going on with this too.

**Comment by cjmyers** [comment]
Got it!  The problem is you are trying to fetch the agent, but the SBOLDesigner agent is not in this document.  You should just fetch the URI and compare.  I've made the change.  Please check.

**Comment by michael13162** [comment]
I actually fixed this bug but pushed it to combinatorial instead of master (it never got copied over).  Sorry.  I hope you didn't have to spend too much time on it.

Closing.
