### ISSUE TITLE
required Java version for SBOLDesigner

### ISSUE THREAD

**Issue by eoberortner** [SynBioDex/SBOLDesigner#82]
Dear SBOLDesigner developers, 
please could you provide any information what Java version is required to execute SBOLDesigner?

I've ran into the following issues:
$ java -jar SBOLDesigner-2.1.jar 
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/clarkparsia/sbol/editor/SBOLDesignerStandalone : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

and here's some information about my Java installed:
$ java -version
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)

Thanks for your help!

Best,
Ernst

**Comment by eoberortner** [comment]
It is quite interesting though, since when executing the SBOLDesigner via double-clicking it in the Finder, then it starts properly.

**Comment by michael13162** [comment]
You can update to Java 1.8 here: http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

Although, if double clicking works, then it'll probably be fine.

**Comment by eoberortner** [comment]
thanks! w/ version 1.8 it works. 
fyi though... in the README.md it says "SBOL designer requires Java 6 or later to be installed on your computer"
Thanks,
Ernst

**Comment by michael13162** [comment]
I will change that.  Thanks for the heads up!

**Comment by cjmyers** [comment]
Are we doing anything that requires 1.8?  Is it possible to support older java versions?

**Comment by michael13162** [comment]
I have not taken a look into this.  I can try to get ahold of someone who only has Java 1.7 and lower and see if it works.
